AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  untitled

  Sample SAM Template for untitled

Globals:
  Function:
    Timeout: 3

Parameters:
  PRUEBA:
    Type: String
  PRUEBA2:
    Type: String

Resources:

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:*

  CoAutoSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${AWS::StackName}-Secret"
      SecretString:
        Fn::Sub: |
          {
            "PRUEBA": "${PRUEBA}",
            "PRUEBA2": "${PRUEBA2}"
          }

  UsApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: UsApi
      StageName: Prod

  GetDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_data_user/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        GetData:
          Type: Api
          Properties:
            RestApiId: !Ref UsApi
            Path: /geeet
            Method: get

Outputs:
  GetDataApiUrl:
    Description: "API Gateway endpoint URL with path get_data for Prod stage to Student Model"
    Value: !Sub "https://${UsApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/geeet"
